@startuml

hide time-axis
concise "Button Command" as button
binary "TASK 1" as t1
binary "TASK 2" as t2
binary "TASK 3" as t3
binary "TASK 4" as t4


@0

@2
button is "TURN LEFT"
button -> t4
@10
t4 is high
t4 -> t1 : blink left
t1 is high
t4 -> t2 : blink right
t2 is high
t4 -> t3 : tick
t3 is high
@11 
t4 is low
@12
t1 is low
t2 is low
t3 is low

@20
t4 is high
t4 -> t1 : blink left
t1 is high
t4 -> t2 : blink right
t2 is high
t4 -> t3 : tick
t3 is high
@21 
t4 is low
@22
t1 is low
t2 is low
t3 is low
@enduml