@startuml

hide time-axis
concise "Button Command" as button
binary "TASK 1" as t1
binary "TASK 2" as t2
binary "TASK 3" as t3
binary "TASK 4" as t4


@0

@2
t4@2 <-> @12 : {0.5 sec}
button is "HAZARD"
button -> t4
t4 is high
t4 -> t1 : blink left on
t1 is high
t4 -> t2 : blink right on
t2 is high
t4 -> t3 : Tick
t3 is high
@3 
t4 is low
@4
t1 is low
t2 is low
t3 is low

@12
t4@12 <-> @22 : {0.5 sec}
t4 is high
t4 -> t1 : blink left off
t1 is high
t4 -> t2 : blink right off
t2 is high
t4 -> t3 : Tock
t3 is high
@13 
t4 is low
@14
t1 is low
t2 is low
t3 is low

@22
t4 is high
t4 -> t1 : blink left on
t1 is high
t4 -> t2 : blink right on
t2 is high
t4 -> t3 : Tick
t3 is high
@23 
t4 is low
@24
t1 is low
t2 is low
t3 is low
@enduml